// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:LojaVirtual.Models.Produto.Imagens")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:LojaVirtual.Repositories.ClienteRepository.ObterTodosClientes(System.Nullable{System.Int32},System.String)~X.PagedList.IPagedList{LojaVirtual.Models.Cliente}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:LojaVirtual.Repositories.ProdutoRepository.ObterTodosProdutos(System.Nullable{System.Int32},System.String)~X.PagedList.IPagedList{LojaVirtual.Models.Produto}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:LojaVirtual.Repositories.Contracts.IImagemRepository.Cadastrar(LojaVirtual.Models.Imagem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:LojaVirtual.Migrations.ProdutoImagem.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:LojaVirtual.Migrations.ProdutoImagem.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:LojaVirtual.Libraries.Arquivo.GerenciadorArquivo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:LojaVirtual.Libraries.Arquivo.GerenciadorArquivo.CadastrarImagemProduto(Microsoft.AspNetCore.Http.IFormFile)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:LojaVirtual.Libraries.Middleware.ValidateAntiForgeryTokenMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:LojaVirtual.Libraries.Middleware.ValidateAntiForgeryTokenMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:LojaVirtual.Libraries.bug.CurrentDirectoryHelpers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1060:Move pinvokes to native methods class", Justification = "<Pending>", Scope = "type", Target = "~T:LojaVirtual.Libraries.bug.CurrentDirectoryHelpers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:LojaVirtual.Program")]
